### ISSUE TITLE
Error: FFmpeg error: Error opening filters!

### ISSUE THREAD

**Issue by WeeJeWel** [trenskow/stream-transcoder.js#18]
On OS X Yosemite with `ffmpeg v2.7.1-tessus`:

```javascript
var stream = fs
	.createReadStream( './armin.mp3' )
	.pipe( new Lame.Decoder )

var transcoder = new Transcoder(stream)
    .audioCodec('mp3')
    .sampleRate(48000)
    .channels(2)
    .audioBitrate(128 * 1000)
    .format('wav')
    .stream()
	.pipe(new Speaker({
		channels: 2,          // 2 channels
		bitDepth: 16,         // 16-bit samples
		sampleRate: 48000     // 44,100 Hz sample rate
	}));
```

results in

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: FFmpeg error: Error opening filters!
    at ChildProcess.<anonymous> (/Users/emile/Desktop/audiostream/node_modules/stream-transcoder/lib/transcoder.js:264:28)
    at ChildProcess.emit (events.js:129:20)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

Any clue?

**Comment by WeeJeWel** [comment]
Never mind, I am stupid. Still had Lame decoder in place :')
